-- =========================================================================
-- 0023  Demo activity so the app is fully explorable before it has users.
--
-- THIS IS TEMPORARY DATA. It exists so the gated features (consensus scoring,
-- "You vs. the room", MOST DIVIDED, the leaderboard, the Pickup recap) can be
-- exercised and critiqued while real usage is still ~zero. Remove it with:
--
--     select public.mp_demo_teardown();
--
-- Every row this migration writes is identifiable by a 'demo_' prefix on its
-- client id, which is what makes that one call sufficient. Nothing here alters
-- schema, and the curated themes from 0022 are CONTENT, not demo data -- the
-- teardown deliberately leaves them standing.
--
-- Boards are generated, not random. A random board puts Michael Jordan in F
-- tier and makes every item a coin flip, which would make the compare screen
-- impossible to evaluate. Instead each theme has a defensible baseline ranking
-- perturbed by personas with stated biases (old-head, ring-counter, modern
-- lean, stat-head), and each theme declares how much of the S..F range it
-- actually uses -- an all-time-greats set is top-heavy and compresses into
-- S..B, while franchise-tiers legitimately runs to F. See scratchpad
-- gen_demo.py; the generator is deterministic (fixed seed).
--
-- Honesty note: while this data is live, "matched the room" is measured partly
-- against invented opinions. That is an accepted, explicit trade for being able
-- to test the product, and it is why teardown is one call rather than a chore.
-- =========================================================================

create or replace function public.mp_demo_teardown()
returns table (deleted_from text, n bigint) language plpgsql as $$
begin
  return query
  with a as (delete from public.mp_party_answers pa
              using public.mp_party_sessions ps
              where ps.id = pa.session_id and ps.host_client_id like 'demo\_%' returning 1),
       b as (delete from public.mp_party_members  where client_id        like 'demo\_%' returning 1),
       c as (delete from public.mp_party_sessions where host_client_id   like 'demo\_%' returning 1),
       d as (delete from public.mp_attempts       where player_client_id like 'demo\_%' returning 1),
       e as (delete from public.mp_tier_lists     where author_client_id like 'demo\_%' returning 1),
       f as (delete from public.mp_lists          where author_client_id like 'demo\_%' returning 1)
  select 'mp_party_answers',  count(*)::bigint from a
  union all select 'mp_party_members',  count(*)::bigint from b
  union all select 'mp_party_sessions', count(*)::bigint from c
  union all select 'mp_attempts',       count(*)::bigint from d
  union all select 'mp_tier_lists',     count(*)::bigint from e
  union all select 'mp_lists',          count(*)::bigint from f;
end $$;

comment on function public.mp_demo_teardown() is
  'Removes all seeded demo activity (any client id prefixed demo_). Leaves curated themes and real user data untouched. Safe to run repeatedly.';
-- generated by scratchpad/gen_demo.py -- do not hand-edit
-- tier strings are positional against item_set order (verified against DB)

-- themes: 120 boards
insert into public.mp_tier_lists (topic_id, author_client_id, author_label, assignments, created_at)
select t.id, d.cid, d.label,
       (select jsonb_object_agg(e.value->>'key', substr(d.tiers, e.ord::int, 1))
          from jsonb_array_elements(t.item_set) with ordinality e(value, ord)),
       now() - (d.hrs || ' hours')::interval
from (values
  ('all-time-dunkers','demo_1467b3a16879','BenchMobBrian','SSASABBCAC',0),
  ('all-time-dunkers','demo_d331676bb89b','StatHead22','SSSAACCDBD',7),
  ('all-time-dunkers','demo_0a82d04abb42','AnalyticsAmy','SSSAACCDBD',14),
  ('all-time-dunkers','demo_2ce1964bcd57','HoopsDad77','SSASACCDBD',21),
  ('all-time-dunkers','demo_cb70299419d9','BoxScoreBecca','SSASACCDBD',28),
  ('all-time-dunkers','demo_1933438e0d4e','CasualCarl','SSASCBDDAC',35),
  ('all-time-dunkers','demo_8aa3424f5309','BarstoolBenny','SSAAABBCSC',42),
  ('all-time-dunkers','demo_4da29c448bea','SixthManSam','SASSAACBBC',49),
  ('what-if-careers','demo_01fd18e910f4','BoxScoreBecca','BAACDBACD',56),
  ('what-if-careers','demo_e3afe76a2ae2','PrimeTimePat','AABCDBACD',63),
  ('what-if-careers','demo_f2311ed970d1','BenchMobBrian','SSACCBSAB',70),
  ('what-if-careers','demo_5338137f8251','CasualCarl','BBCFFDBDC',77),
  ('what-if-careers','demo_cee8d830962e','CourtVision','BBCDFCBDF',84),
  ('what-if-careers','demo_0781fc7de594','RingCounter','SSABCASBC',91),
  ('what-if-careers','demo_02ff19a53d0e','BarstoolBenny','CBBDFCBDF',98),
  ('aughts-superstars','demo_6611d9213fd8','PrimeTimePat','SSSAAABBCC',105),
  ('aughts-superstars','demo_4b52df356513','SixthManSam','SSAAASBBCC',112),
  ('aughts-superstars','demo_0bbd4191bd87','DeepCutDee','SSAASBABCC',119),
  ('aughts-superstars','demo_6eecd04defe0','TheProfessor','SSSASAABBB',126),
  ('aughts-superstars','demo_01721917ebac','NostalgiaNate','SSSAAABCBC',133),
  ('aughts-superstars','demo_f772ceaa7afd','StatHead22','AAABBBCCDD',140),
  ('aughts-superstars','demo_410bd1f17580','CasualCarl','SSSAAACBBC',147),
  ('aughts-superstars','demo_6fac517fb2bb','RingCounter','AAACBBDBCD',154),
  ('aughts-superstars','demo_aef96951d7c1','BenchMobBrian','AABBABCDCD',161),
  ('tens-point-guards','demo_060235591b23','BarstoolBenny','SSBASCDBD',168),
  ('tens-point-guards','demo_ed5ee024d95d','PrimeTimePat','SSASABCBC',175),
  ('tens-point-guards','demo_843c6b2ff8bb','HoopsDad77','SSSABBDDC',182),
  ('tens-point-guards','demo_46931c037835','TheProfessor','SSSABBDDC',189),
  ('tens-point-guards','demo_8b6f6cd76267','BenchMobBrian','SSCABSDBD',196),
  ('tens-point-guards','demo_6c4e17edea26','NostalgiaNate','SSBASBDDC',203),
  ('tens-point-guards','demo_1c284c4e2a57','CourtVision','AAABCCFDF',210),
  ('tens-point-guards','demo_b4a55e4dc2b3','StatHead22','SSSABBDCD',217),
  ('tens-point-guards','demo_24ac56a2b754','RingCounter','SABSSCDBD',224),
  ('franchise-tiers','demo_a58b0438fb27','RingCounter','SSBASDCBFF',231),
  ('franchise-tiers','demo_5c1a281b04c5','DeepCutDee','SSABSFCBFD',238),
  ('franchise-tiers','demo_4b8fcfc70bcb','PrimeTimePat','SSASBCDBFF',245),
  ('franchise-tiers','demo_286bda704408','BarstoolBenny','SSBASDBCFF',252),
  ('franchise-tiers','demo_4bb0b5ff24c7','StatHead22','SSAASCBCDD',259),
  ('franchise-tiers','demo_44c67412b98a','SixthManSam','AAABBFDCDF',266),
  ('franchise-tiers','demo_c1d5b0e03e6e','BoxScoreBecca','AABBAFDCDF',273),
  ('all-time-greats','demo_84c5492bec82','SixthManSam','AAABACBBCC',280),
  ('all-time-greats','demo_2b04023b99da','AnalyticsAmy','SSSSSASAAA',287),
  ('all-time-greats','demo_202a7c3e76dc','CasualCarl','SSSSSAASAA',294),
  ('all-time-greats','demo_19e50071bcdc','HoopsDad77','SSSASBAABB',301),
  ('all-time-greats','demo_998d1b86d57a','BoxScoreBecca','SSSSABAABB',308),
  ('all-time-greats','demo_53286de361ca','TheProfessor','SSSASBAABB',315),
  ('all-time-greats','demo_d70aae353bf6','CourtVision','AAAABCBBCC',322),
  ('ring-or-bust','demo_5bc58c63ad3b','AnalyticsAmy','AAABDBCCDB',329),
  ('ring-or-bust','demo_955b28bc8926','BarstoolBenny','SSSABBACCA',336),
  ('ring-or-bust','demo_02082cb7138b','NostalgiaNate','AAABCBCDDB',343),
  ('ring-or-bust','demo_cf56e3132614','HoopsDad77','SSAABABCCS',350),
  ('ring-or-bust','demo_382ea5f080da','BoxScoreBecca','SSSABAABBS',357),
  ('ring-or-bust','demo_9a4310b21c82','BenchMobBrian','SSSABBACCA',364),
  ('ring-or-bust','demo_d80ee97a7f86','RingCounter','SSSACABBCA',371),
  ('clutch-performers','demo_bc736322096d','NostalgiaNate','SSASABCABC',378),
  ('clutch-performers','demo_65888308b5a0','PrimeTimePat','SSSABAABCC',385),
  ('clutch-performers','demo_79a51e469387','SixthManSam','SSAASABBCC',392),
  ('clutch-performers','demo_b284675e1756','AnalyticsAmy','SSSASABABB',399),
  ('clutch-performers','demo_28fbbef55e83','TheProfessor','SSSSAAABBB',406),
  ('clutch-performers','demo_04f9e10b2630','RingCounter','SSSABAABCC',413),
  ('clutch-performers','demo_df6fb8d6cf15','CasualCarl','SSSSABABAB',420),
  ('clutch-performers','demo_8b456aa6ac9b','BarstoolBenny','SSASAABCCB',427),
  ('clutch-performers','demo_0b816d09f4b8','HoopsDad77','AAABBBDCDC',434),
  ('pure-scorers','demo_09688c2fcba5','CasualCarl','SSAASBBACC',441),
  ('pure-scorers','demo_75a2b5294809','BenchMobBrian','SSASACABCB',448),
  ('pure-scorers','demo_158780b70f52','PrimeTimePat','SSSAACBACB',455),
  ('pure-scorers','demo_6e3b2898c1b3','AnalyticsAmy','AABADCCBBD',462),
  ('pure-scorers','demo_df15c24b9287','TheProfessor','SSSAABBACC',469),
  ('pure-scorers','demo_492aade8e069','SixthManSam','SSSABCAABC',476),
  ('pure-scorers','demo_4d0260e4f6a8','CourtVision','SSASACBABC',483),
  ('floor-generals','demo_e61e25b0d027','DeepCutDee','SSSAASBBBA',490),
  ('floor-generals','demo_c7e5154ba560','RingCounter','SSAASSABBB',497),
  ('floor-generals','demo_3908fdd3e8ed','PrimeTimePat','SSSAASABBB',4),
  ('floor-generals','demo_6b0cd54b02e5','BoxScoreBecca','AABBBACDCD',11),
  ('floor-generals','demo_4834e468fe51','HoopsDad77','AABBCACDDB',18),
  ('floor-generals','demo_45537bfb89ee','CasualCarl','SABSASACCB',25),
  ('floor-generals','demo_f909dbeae8f0','TheProfessor','AABBBACDDC',32),
  ('floor-generals','demo_cea1636318f4','SixthManSam','SSSAASBBAB',39),
  ('floor-generals','demo_8ec92a5b1cb7','NostalgiaNate','AABBCACDDB',46),
  ('lockdown-defenders','demo_48da8df9b405','AnalyticsAmy','SSBAASCCAB',53),
  ('lockdown-defenders','demo_8a68974f5501','StatHead22','SSASASBBAB',60),
  ('lockdown-defenders','demo_b58f4a839675','HoopsDad77','AACBBADDBC',67),
  ('lockdown-defenders','demo_ec93f6a4d79f','CourtVision','SSCAASBCAB',74),
  ('lockdown-defenders','demo_77eb0a08d4c2','CasualCarl','SSABAACCSB',81),
  ('lockdown-defenders','demo_9836525f6aeb','PrimeTimePat','SSBSASBBAA',88),
  ('lockdown-defenders','demo_578e8fbeeb96','DeepCutDee','SSBSAABCAC',95),
  ('greatest-big-men','demo_7e287519a441','AnalyticsAmy','SSASAACBBC',102),
  ('greatest-big-men','demo_5b7a4475b633','BenchMobBrian','SSAASABCBC',109),
  ('greatest-big-men','demo_8072ed914f2b','HoopsDad77','SSASSAABBB',116),
  ('greatest-big-men','demo_fa534a8b1c38','DeepCutDee','SSASAABBCC',123),
  ('greatest-big-men','demo_a45f448e1596','RingCounter','SSASAABCBC',130),
  ('greatest-big-men','demo_df5f0e701e4b','SixthManSam','SSASAABCBC',137),
  ('greatest-big-men','demo_d5360a2050cf','BoxScoreBecca','SSASABBCAC',144),
  ('greatest-big-men','demo_0e1047036fc4','BarstoolBenny','SSAASBACCB',151),
  ('international-greats','demo_979e1a1649c5','AnalyticsAmy','SSSAAACBCB',158),
  ('international-greats','demo_7e752d7df4f5','SixthManSam','SSSASABBBA',165),
  ('international-greats','demo_970e9ceba983','BarstoolBenny','SSSAACCBBA',172),
  ('international-greats','demo_5c09135ca4d6','DeepCutDee','SSSABACBCA',179),
  ('international-greats','demo_f94c01e433b0','StatHead22','SSSAAACBCB',186),
  ('international-greats','demo_e7e8e5b2f748','RingCounter','SSSAACCBBA',193),
  ('international-greats','demo_23505267f63b','BoxScoreBecca','SSSAABCCBA',200),
  ('international-greats','demo_c34fc99e3b58','CasualCarl','SSSAACBBCA',207),
  ('international-greats','demo_91aca462177a','BenchMobBrian','SSSAAABBCC',214),
  ('greatest-coaches','demo_448f4be0168f','DeepCutDee','SSSSABBAAB',221),
  ('greatest-coaches','demo_872712c4aa25','StatHead22','SSSAACCBAB',228),
  ('greatest-coaches','demo_518c8ece886c','CasualCarl','SASSACCBAB',235),
  ('greatest-coaches','demo_b9a2b6435297','BenchMobBrian','SSASACCBAB',242),
  ('greatest-coaches','demo_5c94afa4dbd0','SixthManSam','AABABDDCBC',249),
  ('greatest-coaches','demo_db5cf72cfc25','PrimeTimePat','SSASABCBAC',256),
  ('greatest-coaches','demo_0d2cc3f20120','HoopsDad77','SSASABCBAC',263),
  ('greatest-coaches','demo_4b7e90ab7588','AnalyticsAmy','SSASACCBAB',270),
  ('greatest-teams','demo_dcadd2e3a95e','NostalgiaNate','ABAABBCDDC',277),
  ('greatest-teams','demo_bdb54bd8657f','SixthManSam','AABABBCCDD',284),
  ('greatest-teams','demo_d0a65397080f','RingCounter','AABABBCDDC',291),
  ('greatest-teams','demo_1bd2c43e5d12','BenchMobBrian','SSASAABCCB',298),
  ('greatest-teams','demo_6793df56c7a5','PrimeTimePat','SSSAAABCCB',305),
  ('greatest-teams','demo_e53e11185bcf','HoopsDad77','ABAABBCDDC',312),
  ('greatest-teams','demo_6b5a5ecf2033','AnalyticsAmy','SSASAABCCB',319),
  ('greatest-teams','demo_56745578a0ab','CourtVision','SSASACABCB',326),
  ('greatest-teams','demo_6aba7f4c1b78','TheProfessor','SSASAABCCB',333)
) as d(ref, cid, label, tiers, hrs)
join public.mp_tier_themes th on th.slug = d.ref
join public.mp_tier_topics t on t.theme_id = th.id and t.kind = 'theme'
on conflict do nothing;

-- dailies: 24 boards
insert into public.mp_tier_lists (topic_id, author_client_id, author_label, assignments, created_at)
select t.id, d.cid, d.label,
       (select jsonb_object_agg(e.value->>'key', substr(d.tiers, e.ord::int, 1))
          from jsonb_array_elements(t.item_set) with ordinality e(value, ord)),
       now() - (d.hrs || ' hours')::interval
from (values
  ('daily_2026-07-30','demo_b3bd83134c63','BoxScoreBecca','CSBADSBSFF',0),
  ('daily_2026-07-30','demo_f2a74688105a','SixthManSam','DACBFABADF',3),
  ('daily_2026-07-30','demo_9d38e6ecaec8','StatHead22','CSBAFSBSDF',6),
  ('daily_2026-07-30','demo_0dd2db7fb19d','AnalyticsAmy','CSBADSASCD',9),
  ('daily_2026-07-30','demo_4be9dc6b7eeb','DeepCutDee','CABSDSASCD',12),
  ('daily_2026-07-30','demo_88ece4c49ab2','CourtVision','CSBADSASCD',15),
  ('daily_2026-07-31','demo_2bdccf4e686e','AnalyticsAmy','DBDSSCACSA',18),
  ('daily_2026-07-31','demo_bc2582356542','BoxScoreBecca','FBFSSCBDSA',21),
  ('daily_2026-07-31','demo_2e1a84db0572','StatHead22','DADSSCACSB',24),
  ('daily_2026-07-31','demo_b4a80364eac2','DeepCutDee','FCFAADBDAB',27),
  ('daily_2026-07-31','demo_dbd8d937ddf3','CasualCarl','FBFSSDCASB',30),
  ('daily_2026-07-31','demo_2f86bbdfcca0','CourtVision','DBDSSCACSA',33),
  ('daily_2026-08-01','demo_4f78bbf0abd4','CourtVision','SACSFBDFBS',36),
  ('daily_2026-08-01','demo_76f09c43123c','DeepCutDee','SABSFCFDBS',39),
  ('daily_2026-08-01','demo_ef6f621ff570','AnalyticsAmy','SACSDACDBS',42),
  ('daily_2026-08-01','demo_896c5f1dbd1f','RingCounter','SACSFBDFBS',45),
  ('daily_2026-08-01','demo_614e5f264494','NostalgiaNate','SACSFBDFBS',48),
  ('daily_2026-08-01','demo_51977a9d2295','SixthManSam','ABFAFBDDCA',51),
  ('daily_2026-08-02','demo_fb97453468b7','PrimeTimePat','DBSSDACA',54),
  ('daily_2026-08-02','demo_f1adee582aab','SixthManSam','FDAAFBCB',57),
  ('daily_2026-08-02','demo_e81aa224fa55','TheProfessor','DCSSDABA',0),
  ('daily_2026-08-02','demo_d0f6e11f75ef','NostalgiaNate','CDSSDBAA',3),
  ('daily_2026-08-02','demo_93a1f7b4509b','BenchMobBrian','DCSSDAAB',6),
  ('daily_2026-08-02','demo_a5172df2d340','CasualCarl','BCSSCAAS',9)
) as d(ref, cid, label, tiers, hrs)
join public.mp_tier_topics t on t.share_token = d.ref
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- Leaderboard rows. Derived from existing challenges rather than hardcoded ids.
-- Label/time are hashed from the challenge UUID, NOT length(prompt): the first
-- attempt used prompt length and produced identical twin rows at ranks 1 and 2
-- whenever two challenges happened to share a prompt length.
insert into public.mp_attempts
  (challenge_id, player_client_id, player_label, status,
   correct_count, strikes, elapsed_ms, ranking_time_ms, started_at, finished_at)
select c.id,
       'demo_' || substr(h, 1, 12),
       (array['HoopsDad77','CourtVision','RingCounter','StatHead22','BarstoolBenny',
              'TheProfessor','SixthManSam','NostalgiaNate','AnalyticsAmy','CasualCarl',
              'DeepCutDee','PrimeTimePat','BenchMobBrian','BoxScoreBecca'])
         [1 + (('x' || substr(h, 1, 8))::bit(32)::bigint % 14)],
       case when ('x' || substr(h, 9, 8))::bit(32)::bigint % 5 = 0 then 'eliminated' else 'completed' end,
       greatest(1, c.answer_target - (('x' || substr(h, 17, 4))::bit(16)::int % 3))::smallint,
       case when ('x' || substr(h, 9, 8))::bit(32)::bigint % 5 = 0 then 3
            else (('x' || substr(h, 21, 4))::bit(16)::int % 3) end::smallint,
       35000 + (('x' || substr(h, 25, 7))::bit(28)::bigint % 165000)::int,
       35000 + (('x' || substr(h, 25, 7))::bit(28)::bigint % 165000)::int,
       now() - ((('x' || substr(h, 13, 4))::bit(16)::int % 168) || ' hours')::interval,
       now() - ((('x' || substr(h, 13, 4))::bit(16)::int % 168) || ' hours')::interval + interval '4 minutes'
from public.mp_challenges c
cross join generate_series(1, 4) as n
cross join lateral (select md5(c.id::text || ':' || n::text) as h) hh
where c.answer_target is not null;


-- ---------------------------------------------------------------------------
-- One finished Pickup session so the recap screen renders.
--
-- answers_snapshot is populated deliberately: without it the recap's "You
-- missed:" list -- the payoff of that screen -- has nothing to draw from.
-- Durant / Luka / Harden / Kidd are left UNFOUND on purpose so the list lands.
--
-- Member labels are clean. An earlier pass stored them as 'demo:Sam' so the
-- teardown could find them by prefix, and it rendered verbatim in the recap's
-- contributor bars. The teardown now joins to the session's demo host_client_id
-- instead, which keeps the marker out of the UI entirely.
with s as (
  insert into public.mp_party_sessions
    (code, share_token, prompt, target, status, time_limit_s, misses,
     host_client_id, host_token, started_at, ends_at, ended_at, expires_at, answers_snapshot)
  values ('DEMO42','demo_party_recap','Name 25 players drafted in the top 3',25,
          'ended',300,39,'demo_partyhost01','demo_hosttoken_recap',
          now() - interval '2 hours', now() - interval '115 minutes',
          now() - interval '115 minutes', now() + interval '30 days',
   '[{"player_key":"lebronjames","display_name":"LeBron James","accepted":["lebronjames","james"],"rarity_tier":"common","rarity_score":99},
     {"player_key":"michaeljordan","display_name":"Michael Jordan","accepted":["michaeljordan","jordan"],"rarity_tier":"common","rarity_score":98},
     {"player_key":"magicjohnson","display_name":"Magic Johnson","accepted":["magicjohnson","magic"],"rarity_tier":"common","rarity_score":95},
     {"player_key":"shaquilleoneal","display_name":"Shaquille O''Neal","accepted":["shaquilleoneal","shaq"],"rarity_tier":"common","rarity_score":94},
     {"player_key":"alleniverson","display_name":"Allen Iverson","accepted":["alleniverson","iverson"],"rarity_tier":"common","rarity_score":92},
     {"player_key":"timduncan","display_name":"Tim Duncan","accepted":["timduncan","duncan"],"rarity_tier":"common","rarity_score":93},
     {"player_key":"kareemabduljabbar","display_name":"Kareem Abdul-Jabbar","accepted":["kareemabduljabbar","kareem"],"rarity_tier":"common","rarity_score":97},
     {"player_key":"hakeemolajuwon","display_name":"Hakeem Olajuwon","accepted":["hakeemolajuwon","olajuwon"],"rarity_tier":"uncommon","rarity_score":88},
     {"player_key":"davidrobinson","display_name":"David Robinson","accepted":["davidrobinson","robinson"],"rarity_tier":"uncommon","rarity_score":85},
     {"player_key":"patrickewing","display_name":"Patrick Ewing","accepted":["patrickewing","ewing"],"rarity_tier":"uncommon","rarity_score":84},
     {"player_key":"chriswebber","display_name":"Chris Webber","accepted":["chriswebber","webber"],"rarity_tier":"uncommon","rarity_score":78},
     {"player_key":"derrickrose","display_name":"Derrick Rose","accepted":["derrickrose","rose"],"rarity_tier":"uncommon","rarity_score":80},
     {"player_key":"yaoming","display_name":"Yao Ming","accepted":["yaoming","yao"],"rarity_tier":"uncommon","rarity_score":77},
     {"player_key":"dwighthoward","display_name":"Dwight Howard","accepted":["dwighthoward","howard"],"rarity_tier":"uncommon","rarity_score":79},
     {"player_key":"anferneehardaway","display_name":"Anfernee Hardaway","accepted":["anferneehardaway","pennyhardaway","penny"],"rarity_tier":"rare","rarity_score":70},
     {"player_key":"gregoden","display_name":"Greg Oden","accepted":["gregoden","oden"],"rarity_tier":"rare","rarity_score":62},
     {"player_key":"sambowie","display_name":"Sam Bowie","accepted":["sambowie","bowie"],"rarity_tier":"rare","rarity_score":58},
     {"player_key":"darkomilicic","display_name":"Darko Milicic","accepted":["darkomilicic","darko"],"rarity_tier":"deep_cut","rarity_score":40},
     {"player_key":"michaelolowokandi","display_name":"Michael Olowokandi","accepted":["michaelolowokandi","olowokandi"],"rarity_tier":"deep_cut","rarity_score":38},
     {"player_key":"kwamebrown","display_name":"Kwame Brown","accepted":["kwamebrown","kwame"],"rarity_tier":"deep_cut","rarity_score":42},
     {"player_key":"pervisellison","display_name":"Pervis Ellison","accepted":["pervisellison","ellison"],"rarity_tier":"deep_cut","rarity_score":30},
     {"player_key":"kevindurant","display_name":"Kevin Durant","accepted":["kevindurant","durant","kd"],"rarity_tier":"common","rarity_score":96},
     {"player_key":"jamesharden","display_name":"James Harden","accepted":["jamesharden","harden"],"rarity_tier":"common","rarity_score":89},
     {"player_key":"lukadoncic","display_name":"Luka Doncic","accepted":["lukadoncic","luka","doncic"],"rarity_tier":"uncommon","rarity_score":90},
     {"player_key":"jasonkidd","display_name":"Jason Kidd","accepted":["jasonkidd","kidd"],"rarity_tier":"uncommon","rarity_score":82}]'::jsonb)
  returning id
), m as (
  insert into public.mp_party_members (session_id, client_id, label, member_token)
  select s.id, 'demo_pm_' || v.n, v.label, 'demo_mt_' || v.n
  from s cross join (values (1,'Dave'),(2,'Sam'),(3,'Priya'),(4,'Marcus')) as v(n, label)
  returning id, session_id, label
)
insert into public.mp_party_answers
  (session_id, player_key, display_name, rarity_tier, member_id, member_label, created_at)
select m.session_id, public.mp_normalize(a.nm), a.nm, a.rarity, m.id, m.label,
       now() - interval '2 hours' + ((a.ord * 11) || ' seconds')::interval
from (values
  ('LeBron James','common',1),('Michael Jordan','common',2),('Magic Johnson','common',3),
  ('Shaquille O''Neal','common',4),('Allen Iverson','common',5),('Tim Duncan','common',6),
  ('Kareem Abdul-Jabbar','common',7),('Hakeem Olajuwon','uncommon',8),('David Robinson','uncommon',9),
  ('Patrick Ewing','uncommon',10),('Chris Webber','uncommon',11),('Derrick Rose','uncommon',12),
  ('Yao Ming','uncommon',13),('Dwight Howard','uncommon',14),('Anfernee Hardaway','rare',15),
  ('Greg Oden','rare',16),('Sam Bowie','rare',17),('Darko Milicic','deep_cut',18),
  ('Michael Olowokandi','deep_cut',19),('Kwame Brown','deep_cut',20),('Pervis Ellison','deep_cut',21)
) as a(nm, rarity, ord)
join m on m.label = (array['Dave','Sam','Priya','Marcus'])[1 + (a.ord % 4)];
