-- 0045 · Ranked leader sheets
--
-- "Name the 8 Bulls with the most career assists" has never been buildable.
-- challenge_build rejects mode:"top8" because top-8 answers come from
-- perfect_sheet_answers, in a table the app does not own.
--
-- That framing is wrong. perfect_sheets holds ten rows, seven of them ours, and
-- the app already owns a complete parallel sheet stack — mp_roster_sheets +
-- mp_roster_pool, generated by mp_build_filtered_roster through mp_facet_match.
-- Top-8 was simply built first, against the other table, and never moved.
--
-- Read the two play paths side by side and they are the same game: both ask
-- whether a guess matches an entry's `accepted` aliases, with an identical
-- matcher. They differ in two properties only — whether the answer set is open
-- or closed, and whether it is ordered. So:
--
--     A leaders sheet is a roster sheet whose pool IS the answer set,
--     ordered by a metric.
--
-- Ranked vs unranked is a property of a sheet, not a species of game.
--
-- ⚠️ THE DECISION THIS ALL RESTS ON: a metric is an ORDER BY, not a predicate.
-- mp_facet_match is therefore NOT touched by this migration. No existing pool
-- can shift, so the 0039 rule ("re-cut every sheet whenever mp_facet_match
-- changes") is not triggered and the 96 shipped sheets stay exactly as cut.
-- If a future change ever makes a metric filter rows, that rule comes back.
--
-- Everything here is additive: three new facet columns, two new nullable pool
-- columns, and function bodies. No existing row is modified.

begin;

-- ---------------------------------------------------------------- 1. facets
-- career_assists / rebounds / blocks are already in
-- vw_trivia_player_career_summary; mp_rebuild_facets simply was not selecting
-- them. Points and games were, which is why those two metrics could have been
-- built all along and the other three could not.
alter table public.mp_player_facets
  add column if not exists career_assists  numeric,
  add column if not exists career_rebounds numeric,
  add column if not exists career_blocks   numeric;

create or replace function public.mp_rebuild_facets()
 returns bigint
 language plpgsql
as $function$
declare n bigint;
begin
  truncate public.mp_player_facets;

  insert into public.mp_player_facets (
    player_key, player_name, name_key, last_name_key,
    first_season, last_season, seasons_n, games_played, career_points,
    career_assists, career_rebounds, career_blocks,
    positions, teams, decades, colleges,
    allstar_n, allnba_n, alldef_n, mvp_n, dpoy_n, roy_n, smoy_n, mip_n,
    rings, hof, draft_pick, draft_round, draft_year, notability)
  select
    v.player_key,
    v.player_name,
    public.mp_normalize(v.player_name),
    public.mp_normalize(split_part(v.player_name, ' ', -1)),
    n.first_season, n.last_season, n.seasons_n::int, n.games_played, n.career_points,
    v.career_assists, v.career_rebounds, v.career_blocks,
    (select coalesce(array_agg(p order by p), '{}')
       from (select unnest(array['G','F','C']) p) z
      where pci.pos ilike '%'||z.p||'%'),
    coalesce(string_to_array(replace(v.teams_played_for, ' ', ''), ','), '{}'),
    (select coalesce(array_agg(distinct (s/10)*10 order by (s/10)*10), '{}')
       from generate_series(coalesce(n.first_season, 0), coalesce(n.last_season, 0)) s
      where n.first_season is not null),
    (select coalesce(array_agg(distinct btrim(t) order by btrim(t)), '{}')
       from unnest(string_to_array(coalesce(pci.colleges, ''), ',')) t
      where btrim(t) not in ('NA', '')),
    coalesce(n.allstar_n, 0)::int,
    coalesce(n.allnba_n, 0)::int,
    coalesce(eos.alldef, 0),
    coalesce(aw.mvp, 0), coalesce(aw.dpoy, 0), coalesce(aw.roy, 0),
    coalesce(aw.smoy, 0), coalesce(aw.mip, 0),
    coalesce(n.rings, 0)::int, coalesce(n.hof, false),
    n.draft_pick,
    nullif(regexp_replace(coalesce(dr.round, ''), '[^0-9]', '', 'g'), '')::int,
    nullif(regexp_replace(coalesce(dr.season, ''), '[^0-9]', '', 'g'), '')::int,
    n.notability
  from public.vw_trivia_player_career_summary v
  join public.mp_player_notability n on n.player_key = v.player_key
  left join nba_sumitro_raw.player_career_info pci on pci.player_id = v.player_key
  left join (
    select player_id,
           count(*) filter (where award='nba mvp')  as mvp,
           count(*) filter (where award='nba dpoy') as dpoy,
           count(*) filter (where award='nba roy')  as roy,
           count(*) filter (where award='nba smoy') as smoy,
           count(*) filter (where award='nba mip')  as mip
    from nba_sumitro_raw.player_award_shares
    where lower(coalesce(winner,'')) in ('true','t','1','yes')
    group by player_id
  ) aw on aw.player_id = v.player_key
  left join (
    select player_id, count(*)::int as alldef
    from nba_sumitro_raw.end_of_season_teams
    where type = 'All-Defense'
    group by player_id
  ) eos on eos.player_id = v.player_key
  left join (
    select player_id, min(round) as round, min(season) as season
    from nba_sumitro_raw.draft_pick_history
    where coalesce(lg,'NBA') = 'NBA'
    group by player_id
  ) dr on dr.player_id = v.player_key
  where v.season_type = 'REGULAR';

  select count(*) into n from public.mp_player_facets;
  return n;
end $function$;

select public.mp_rebuild_facets();

-- ------------------------------------------------------------ 2. vocabulary
-- The metric whitelist lives in SQL because the pool generator and the
-- playability gate both need it and must agree. ppg is deliberately absent: it
-- needs a min-games eligibility rule, which is a different shape, and the
-- legacy league-wide ppg sheet keeps working where it is.
create or replace function public.mp_is_metric(p text)
 returns boolean language sql immutable
as $function$
  select p is not null and p in ('points','assists','rebounds','blocks','games');
$function$;

-- Takes the facets row rather than a key, so adding a metric later is one
-- more branch here and nothing else. Unknown metric returns null, which the
-- `> 0` guards below turn into "no rows" rather than a wrong board.
create or replace function public.mp_metric_value(m public.mp_player_facets, p_metric text)
 returns numeric language sql immutable
as $function$
  select case p_metric
    when 'points'   then m.career_points
    when 'assists'  then m.career_assists
    when 'rebounds' then m.career_rebounds
    when 'blocks'   then m.career_blocks
    when 'games'    then m.games_played::numeric
    else null end;
$function$;

-- ------------------------------------------------------------- 3. identity
-- `metric` joins the whitelist. An absent metric leaves the key BYTE-IDENTICAL,
-- so no existing sheet's identity moves and the partial unique index on
-- source_params keeps matching what it matched before. A ranked sheet and the
-- unranked sheet for the same filters now have different keys, so they cannot
-- collide — which is what stops the preview promising a count the sheet does
-- not hold (the 0028 invariant).
create or replace function public.mp_facet_key(f jsonb, p_target integer)
 returns jsonb language sql immutable
as $function$
  select coalesce(
           (select jsonb_object_agg(k, f->k)
              from unnest(array['team','position','decade','award','draft',
                                'college','conference','metric']) as k
             where f ? k and f->>k is not null),
           '{}'::jsonb)
         || jsonb_build_object('target', p_target);
$function$;

-- ---------------------------------------------------------- 4. ranked pool
-- ONE generator, shared by the builder, the refiller and the gate — the same
-- "one predicate, two callers" rule 0028 set. Separate copies would let the
-- preview promise a leaders board the sheet does not hold.
--
-- Two rules encoded here:
--   · ties break on player_key, because a leaders board must be reproducible
--   · value > 0, because blocks were not recorded before 1974 and a board of
--     zeroes is not a game
create or replace function public.mp_facet_ranked_pool(f jsonb, p_target integer)
 returns table (
   player_key text, player_name text, games_played integer,
   notability numeric, pool_rank integer, metric_value numeric)
 language sql stable
as $function$
  select m.player_key, m.player_name, m.games_played, m.notability,
         (row_number() over (
            order by public.mp_metric_value(m, f->>'metric') desc, m.player_key))::int,
         public.mp_metric_value(m, f->>'metric')
  from public.mp_facet_match(f, null) m
  where public.mp_is_metric(f->>'metric')
    and public.mp_metric_value(m, f->>'metric') > 0
  order by 5
  limit greatest(coalesce(p_target, 0), 0);
$function$;

-- How many players could legally appear on a ranked board for these filters.
create or replace function public.mp_facet_metric_count(f jsonb)
 returns integer language sql stable
as $function$
  select count(*)::int
  from public.mp_facet_match(f, null) m
  where public.mp_is_metric(f->>'metric')
    and public.mp_metric_value(m, f->>'metric') > 0;
$function$;

-- ------------------------------------------------------------- 5. the pool
-- Nullable on purpose: every one of the 18,839 existing rows is already
-- correct as NULL, so there is no backfill and no re-cut. NULL rank means
-- "unranked pool", which is what every sheet shipped so far is.
alter table public.mp_roster_pool
  add column if not exists "rank"      smallint,
  add column if not exists metric_value numeric;

comment on column public.mp_roster_pool."rank" is
  'Ranked (leader) sheets only. NULL = unranked pool, i.e. every pre-0045 row.';

-- --------------------------------------------------------------- 6. gating
-- Ranked asks are EXACT, not gate-1. The `-1` exists so an open pool holds
-- more than the ask; the top 8 of a filtered set is exactly 8. Difficulty
-- likewise cannot come from a pool/target ratio (they are equal by
-- construction), so it comes from how obscure the LAST name on the board is,
-- reusing the same notability bands as rarity_tier.
create or replace function public.mp_challenge_preview(f jsonb)
 returns jsonb
 language plpgsql
 stable
as $function$
declare
  v_mode   text := coalesce(f->>'mode', 'roster');
  v_want   int  := least(greatest(coalesce((f->>'target')::int, 8), 3), 12);
  v_floor  numeric := coalesce((f->>'min_notability')::numeric, 30);
  v_min_ask constant int := 3;
  v_pool int; v_known int; v_gate int; v_target int;
  v_verdict text; v_diff text := null; v_relax jsonb := null;
  v_unknown text := null;
  v_metric text := f->>'metric';
  v_tail numeric;
  k text; probe jsonb; probe_n int;
  best_k text := null; best_n int := null;
  fall_k text := null; fall_n int := -1;
begin
  if f->>'college' is not null and not exists (
       select 1 from public.mp_player_facets where colleges @> array[f->>'college'])
  then v_unknown := 'college';
  elsif f->>'conference' is not null and not exists (
       select 1 from public.mp_college_conferences where conference = f->>'conference')
  then v_unknown := 'conference';
  elsif v_metric is not null and not public.mp_is_metric(v_metric)
  then v_unknown := 'metric';
  end if;

  if v_unknown is not null then
    return jsonb_build_object(
      'mode', v_mode, 'pool', 0, 'known', 0, 'gate', 0,
      'requested_target', v_want, 'target', null, 'clamped', false,
      'verdict', 'impossible', 'difficulty', null, 'relax', null,
      'unknown_filter', v_unknown, 'min_notability', v_floor, 'min_ask', v_min_ask,
      'ranked', v_metric is not null, 'metric', v_metric);
  end if;

  -- ---- ranked branch: the board is the top N, so the pool is the gate ----
  if v_metric is not null then
    v_pool  := public.mp_facet_metric_count(f);
    v_known := v_pool;                     -- notable by construction; see 0028 notes
    v_gate  := v_pool;
    v_target := least(v_want, v_gate);     -- exact, not gate - 1

    if v_gate < v_min_ask then
      v_verdict := 'impossible'; v_target := null;
      foreach k in array array['team','position','decade','award','draft','college','conference'] loop
        if f ? k and f->>k is not null then
          probe := f - k;
          probe_n := public.mp_facet_metric_count(probe);
          if probe_n >= v_min_ask and (best_n is null or probe_n < best_n) then
            best_n := probe_n; best_k := k;
          end if;
          if probe_n > fall_n then fall_n := probe_n; fall_k := k; end if;
        end if;
      end loop;
      if best_k is null then best_k := fall_k; best_n := fall_n; end if;
      if best_k is not null then
        v_relax := jsonb_build_object('filter', best_k, 'would_give', best_n);
      end if;
    elsif v_gate < v_want then
      v_verdict := 'tight';
    else
      v_verdict := 'ok';
    end if;

    if v_target is not null then
      select min(r.notability) into v_tail
        from public.mp_facet_ranked_pool(f, v_target) r;
      v_diff := case
        when v_tail >= 55 then 'easy'
        when v_tail >= 38 then 'normal'
        when v_tail >= 25 then 'hard'
        else 'brutal' end;
    end if;

    return jsonb_build_object(
      'mode', v_mode, 'pool', v_pool, 'known', v_known, 'gate', v_gate,
      'requested_target', v_want, 'target', v_target,
      'clamped', v_target is not null and v_target < v_want,
      'verdict', v_verdict, 'difficulty', v_diff, 'relax', v_relax,
      'unknown_filter', null, 'min_notability', v_floor, 'min_ask', v_min_ask,
      'ranked', true, 'metric', v_metric);
  end if;

  -- ---- unranked: unchanged from 0027/0029 ----
  v_pool  := public.mp_facet_count(f, null);
  v_known := public.mp_facet_count(f, v_floor);
  v_gate  := case when v_mode = 'top8' then v_pool else v_known end;
  v_target := least(v_want, greatest(v_gate - 1, v_min_ask));

  if v_gate <= v_min_ask then
    v_verdict := 'impossible';
    foreach k in array array['team','position','decade','award','draft','college','conference'] loop
      if f ? k and f->>k is not null then
        probe := f - k;
        probe_n := case when v_mode='top8' then public.mp_facet_count(probe, null)
                        else public.mp_facet_count(probe, v_floor) end;
        if probe_n > v_min_ask and (best_n is null or probe_n < best_n) then
          best_n := probe_n; best_k := k;
        end if;
        if probe_n > fall_n then fall_n := probe_n; fall_k := k; end if;
      end if;
    end loop;
    if best_k is null then best_k := fall_k; best_n := fall_n; end if;
    if best_k is not null then
      v_relax := jsonb_build_object('filter', best_k, 'would_give', best_n);
    end if;
    v_target := null;
  elsif v_gate <= v_target + 2 then
    v_verdict := 'tight';
  else
    v_verdict := 'ok';
  end if;

  if v_target is not null then
    v_diff := case
      when v_gate <= v_target + 2 then 'brutal'
      when v_gate <= v_target * 2 then 'hard'
      when v_gate <= v_target * 5 then 'normal'
      else 'easy' end;
  end if;

  return jsonb_build_object(
    'mode', v_mode, 'pool', v_pool, 'known', v_known, 'gate', v_gate,
    'requested_target', v_want, 'target', v_target,
    'clamped', v_target is not null and v_target < v_want,
    'verdict', v_verdict, 'difficulty', v_diff, 'relax', v_relax,
    'unknown_filter', null, 'min_notability', v_floor, 'min_ask', v_min_ask,
    'ranked', false, 'metric', null);
end $function$;

-- -------------------------------------------------------------- 7. builder
create or replace function public.mp_build_filtered_roster(
    f jsonb, p_prompt text, p_target smallint, p_difficulty text default 'normal')
 returns uuid
 language plpgsql
as $function$
declare sid uuid; k jsonb;
begin
  k := public.mp_facet_key(f, p_target::int);

  if k ? 'metric' and not public.mp_is_metric(k->>'metric') then
    raise exception 'unknown_metric: %', k->>'metric';
  end if;

  select id into sid from public.mp_roster_sheets
   where source_params = k and status = 'approved' limit 1;
  if sid is not null then return sid; end if;

  insert into public.mp_roster_sheets
    (prompt, difficulty, position, team_abbr, decade, target, status, source_params)
  values (p_prompt, p_difficulty,
          case k->>'position' when 'G' then 'Guard' when 'F' then 'Forward' when 'C' then 'Center' end,
          k->>'team', (k->>'decade')::int, p_target, 'approved', k)
  returning id into sid;

  if k ? 'metric' then
    -- Ranked: the pool IS the answer set. rarity still comes from notability so
    -- the existing reveal ("players you could have named") keeps working.
    insert into public.mp_roster_pool
      (sheet_id, player_key, display_name, last_name, rarity_tier, rarity_score,
       games, "rank", metric_value)
    select sid, r.player_key, r.player_name, split_part(r.player_name, ' ', -1),
           case when r.notability >= 55 then 'common'
                when r.notability >= 38 then 'uncommon'
                when r.notability >= 25 then 'rare'
                else 'deep_cut' end,
           coalesce(r.notability, 0)::int, r.games_played, r.pool_rank, r.metric_value
    from public.mp_facet_ranked_pool(k, p_target::int) r;
  else
    insert into public.mp_roster_pool
      (sheet_id, player_key, display_name, last_name, rarity_tier, rarity_score, games)
    select sid, m.player_key, m.player_name, split_part(m.player_name, ' ', -1),
           case when m.notability >= 55 then 'common'
                when m.notability >= 38 then 'uncommon'
                when m.notability >= 25 then 'rare'
                else 'deep_cut' end,
           coalesce(m.notability, 0)::int, m.games_played
    from public.mp_facet_match(k, null) m;
  end if;

  update public.mp_roster_pool p set accepted =
    case when (select count(*) from public.mp_roster_pool q
                where q.sheet_id = sid
                  and public.mp_normalize(q.last_name) = public.mp_normalize(p.last_name)) = 1
         then array[public.mp_normalize(p.display_name), public.mp_normalize(p.last_name)]
         else array[public.mp_normalize(p.display_name)] end
  where p.sheet_id = sid;

  return sid;
end $function$;

-- ------------------------------------------------------------- 8. refiller
-- Must branch identically, or refilling a ranked sheet would silently blow it
-- back out into a full open pool and change a shipped board.
create or replace function public.mp_refill_roster_pool(p_sheet uuid)
 returns integer
 language plpgsql
as $function$
declare k jsonb; t int; n integer;
begin
  select source_params, target into k, t
    from public.mp_roster_sheets where id = p_sheet;
  if k is null then return 0; end if;

  delete from public.mp_roster_pool where sheet_id = p_sheet;

  if k ? 'metric' then
    insert into public.mp_roster_pool
      (sheet_id, player_key, display_name, last_name, rarity_tier, rarity_score,
       games, "rank", metric_value)
    select p_sheet, r.player_key, r.player_name, split_part(r.player_name, ' ', -1),
           case when r.notability >= 55 then 'common'
                when r.notability >= 38 then 'uncommon'
                when r.notability >= 25 then 'rare'
                else 'deep_cut' end,
           coalesce(r.notability, 0)::int, r.games_played, r.pool_rank, r.metric_value
    from public.mp_facet_ranked_pool(k, t) r;
  else
    insert into public.mp_roster_pool
      (sheet_id, player_key, display_name, last_name, rarity_tier, rarity_score, games)
    select p_sheet, m.player_key, m.player_name, split_part(m.player_name, ' ', -1),
           case when m.notability >= 55 then 'common'
                when m.notability >= 38 then 'uncommon'
                when m.notability >= 25 then 'rare'
                else 'deep_cut' end,
           coalesce(m.notability, 0)::int, m.games_played
    from public.mp_facet_match(k, null) m;
  end if;

  update public.mp_roster_pool p set accepted =
    case when (select count(*) from public.mp_roster_pool q
                where q.sheet_id = p_sheet
                  and public.mp_normalize(q.last_name) = public.mp_normalize(p.last_name)) = 1
         then array[public.mp_normalize(p.display_name), public.mp_normalize(p.last_name)]
         else array[public.mp_normalize(p.display_name)] end
  where p.sheet_id = p_sheet;

  select count(*) into n from public.mp_roster_pool where sheet_id = p_sheet;
  return n;
end $function$;

commit;
